# yaml-language-server: $schema=https://blue-build.org
version: 1
name: bazzite-kineticwe
description: Versión Frankenstein definitiva corregida. Repositorios limpios de Don y usuario estándar.

base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: stable

modules:
  # 1. TRANSMUTACIÓN ATÓMICA DE PANTALLA (CON REPOS OFICIALES DE DON SIN DUPLICADOS)
  - type: script
    snippets:
      - |
        bash -c '
        # 1.1 Enlazar los repositorios híbridos oficiales de Don (Sufijo fedora-44 real)
        curl -Lo /etc/yum.repos.d/_copr_lionheartp-Hyprland.repo https://copr.fedorainfracloud.org/coprs/lionheartp/Hyprland/repo/fedora-44/lionheartp-Hyprland.repo
        curl -Lo /etc/yum.repos.d/_copr_theblackdon-kineticwe.repo https://copr.fedorainfracloud.org/coprs/theblackdon/kineticwe/repo/fedora-44/theblackdon-kineticwe-fedora-44.repo
        curl -Lo /etc/yum.repos.d/_copr_theblackdon-noctalia.repo https://copr.fedorainfracloud.org/coprs/theblackdon/noctalia/repo/fedora-44/theblackdon-noctalia.repo
        
        # 1.2 Reemplazo masivo limpio: Purgamos KDE e inyectamos el entorno real moderno de Don
        rpm-ostree override remove kwin kwin-common kwin-libs kglobalacceld kdecoration --install kineticwe --install noctalia
        
        # 1.3 Instalamos las aplicaciones estéticas complementarias en las capas
        rpm-ostree install kitty fish dolphin mpvpaper
        '
  # 2. INYECCIÓN DE USUARIO TRADICIONAL POR BASH SEGURO (SIN HASHES ROTOS)
  - type: script
    snippets:
      - |
        bash -c '
        # 2.1 Creamos la casa física en la raíz del esqueleto
        mkdir -p /var/home/inhumano
        
        # 2.2 Registramos el usuario de forma limpia con Fish por defecto
        useradd -d /var/home/inhumano -M -G wheel -s /usr/bin/fish inhumano
        
        # 2.3 El secreto: Le inyectamos la contraseña temporal en texto plano para que el kernel la asimile
        echo "inhumano:1234" | chpasswd
        
        # 2.4 Clonamos el esqueleto y reparamos los permisos de administrador
        cp -r /etc/skel/. /var/home/inhumano/
        chown -R inhumano:inhumano /var/home/inhumano
        chmod 700 /var/home/inhumano
        
        # 2.5 Cambiar la shell global de useradd a Fish
        sed -i "s/\/bin\/bash/\/usr\/bin\/fish/g" /etc/default/useradd
        '
