# EL FUTURO PLANO ATÓMICO CON RENDIMIENTO CACHYOS (SIN FANTASMAS DE KDE)
base-image: ghcr.io/cachyos/cachyos-bootc   # <--- Buscaremos la etiqueta oficial de CachyOS para bootc
image-version: latest

modules:
  - type: script
    snippets:
      - |
        bash -c '
        # 1. Al ser Cachy/Arch, la instalación se hace con pacman de forma nativa y sin overrides
        # 2. Inyectamos los repos de Don y descargamos el entorno limpio desde cero
        pacman -Syu --noconfirm kineticwe noctalia kitty fish dolphin mpvpaper
        '
