# yaml-language-server: $schema=https://blue-build.org
version: 1
name: bazzite-kineticwe
description: Imagen estilo 'Donzzite' de Bazzite con el entorno KineticWE, Kitty y Fish.

base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: stable

modules:
  # 1. REPOSITORIOS: Habilitamos las fuentes Copr
  - type: copr
    repos:
      - theblackdon/kineticwe
      - lionheartp/Hyprland

  # 2. EL REEMPLAZO (Sintaxis Oficial de BlueBuild):
  # Indicamos al sistema de qué repositorio Copr provienen los reemplazos de KWin
  - type: rpm-ostree
    replace:
      - from-repo: copr:copr.fedorainfracloud.org:theblackdon:kineticwe
        packages:
          - kwin
          - kwin-common
          - kwin-libs
          - kglobalacceld
          - kdecoration

  # 3. PURGA DE BAZZITE
  - type: rpm-ostree
    remove:
      - bazzite-portal
      - bazzite-updater

  # 4. INSTALACIÓN NATIVA
  - type: rpm-ostree
    install:
      - noctalia
      - kitty
      - fish
      - dolphin
      - obs-studio
      - discord

  # 5. CONFIGURACIÓN: Forzar a Fish como shell predeterminada
  - type: script
    scripts:
      - |
        #!/usr/bin/env bash
        set -ox pipefail
        sed -i 's/\/bin\/bash/\/usr\/bin\/fish/g' /etc/default/useradd
